
spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/t2305m_spring}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  servlet:
    context-path: /trainingSouls
  port: 8080

jwt:
  signerKey: "HMgNNiK2cPCkBR1RGd8b7GFVg/qWIW4200CDsuE4WWElu3mQxoUecnFxkOdK2CRd"

vnpay:
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  tmn-code: 22MBY15K
  secret-key: 8HOBMXOV2MHMXX48JQ6QG6WYSGJ9BUO3
  return-url: http://54.251.220.228:8080/trainingSouls/payment/vn-pay-callback
  version: 2.1.0
  command: pay
  order-type: other


paypal:
  client-id: AedSI6RNn6tJKtT5d2BzI-hNqk6tvg7GOBMyvJVCsW_r7jscFtP2k76qOLIkNFRqy13sdyjvkU06v8tI
  secret-id: ECVuqfLoEI1al7b_J73YdVUABdk9JtCfMkJkFrbyVyFyoxmIFAwUT6YikMBS5cZi-2VPUsWuzpEhzhWA
