
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projectSem4
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  servlet:
    context-path: /trainingSouls
  port: 8080

jwt:
  signerKey: "HMgNNiK2cPCkBR1RGd8b7GFVg/qWIW4200CDsuE4WWElu3mQxoUecnFxkOdK2CRd"



